# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  setup_script:
     description: a script that you want to run to configure the host and start your service. Note that service processes need to be backgrounded by the script (must not run in the foreground)
     type: string
     default: ""
  environment_variables:
     description: a set of comma (,) delimited key=value pairs.
     type: string
     default: ""
