# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  setup_script:
     description: a script that you want to run to configure the host and start up your service. Note that scripts will time out after 180s - ensure any daemon processes your script starts are started in the background - for example `nohup ./my-daemon.sh \&> /var/log/my-daemon.log \&`.
     type: string
     default: ""
  environment_variables:
     description: a set of comma (,) delimited key=value pairs.
     type: string
     default: ""
